pipeline{
    agent any
    stages {
        stage('Git Checkout'){
            steps{
                echo "Git Checkout Successfully!";
            }
        }
        stage('Unit testing'){
            steps{
                echo "Unit Test Passed Successfully!";
            }
        }
        stage('Quality Gate'){
            steps{
                echo "Quality Gate Successfully!";
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploy to Server Successfully!";
            }
        }
    }
}